baseURL = 'https://varigergo.hu/'
languageCode = 'hu-HU'
title = 'Vári Gergő'

[markup.goldmark.renderer]
unsafe = true 

[module]
	[[module.imports]]
	path = "github.com/gergovari/vyberpunk"

	[[module.imports]]
	path = "github.com/gergovari/varigergo-shared"
		[[module.imports.mounts]]
		source = "content/"
		target = "content"

[params.matomo]
url = "https://matomo.varigergo.hu"
id = 1

[params.stripe]
key = "pk_live_51MqVpzDJeSyRUjQe1jZ8WNZbhEaLL9QeZeJ4Svfkh7GM6n6va4IVRXLksYKePwL20WN71qwYdJMq85ploaYQAn5t005fDtR25L"
#key = "pk_test_51MqVpzDJeSyRUjQeXckxIaDFRQEIqsdrwUQkcqMRswoAfDxwfjHKTWXnrHk4faya7Jo1nwvcSDEPi7chIiquEBWs00kB3a8QUQ"
backendUrl = "https://stripe.varigergo.hu"
doneUrl = "https://varigergo.hu/checkout-done/stripe"

[params.colors]
	bg = "#0d0d0d"
	text = "#f2f2f2"
	accent = "#590202"
	accent1 = "#F23D3D"
	accent2 = "#F20505"
