baseURL = 'https://varigergo.hu/'
languageCode = 'hu-HU'
title = 'Vári Gergő'

[module]
[[module.imports]]
path = "github.com/gergovari/vyberpunk"
theme = "vyberpunk"

[params.matomo]
url = "https://matomo.varigergo.hu"
id = 1

[params.stripe]
#key = "pk_live_51MqVpzDJeSyRUjQe1jZ8WNZbhEaLL9QeZeJ4Svfkh7GM6n6va4IVRXLksYKePwL20WN71qwYdJMq85ploaYQAn5t005fDtR25L"
key = "pk_test_51MqVpzDJeSyRUjQeXckxIaDFRQEIqsdrwUQkcqMRswoAfDxwfjHKTWXnrHk4faya7Jo1nwvcSDEPi7chIiquEBWs00kB3a8QUQ"
backendUrl = "https://stripe.varigergo.hu"
doneUrl = "https://varigergo.hu/checkout-done/stripe"
