baseURL = 'https://varigergo.hu/'
title = 'Gergő Vári'

[module]
	[[module.imports]]
	path = "github.com/vyberd/vyberpunk"

	[[module.imports]]
	path = "github.com/vyberd/funnels"
	[[module.imports]]
	path = "github.com/vyberd/checkout"
	[[module.imports]]
	path = "github.com/vyberd/questionnaires"

	[[module.imports]]
	path = "github.com/gergovari/varigergo-shared"

[params.matomo]
url = "https://matomo.varigergo.hu"
id = 1

[params.stripe]
key = "pk_live_51MqVpzDJeSyRUjQe1jZ8WNZbhEaLL9QeZeJ4Svfkh7GM6n6va4IVRXLksYKePwL20WN71qwYdJMq85ploaYQAn5t005fDtR25L"
#key = "pk_test_51MqVpzDJeSyRUjQeXckxIaDFRQEIqsdrwUQkcqMRswoAfDxwfjHKTWXnrHk4faya7Jo1nwvcSDEPi7chIiquEBWs00kB3a8QUQ"
backendUrl = "https://stripe.varigergo.hu"
doneUrl = "https://varigergo.hu/checkout-done/stripe"

[params.mautic]
url = "https://mautic.varigergo.hu"
