[[start]]
	name = "blog"
	weight = 5
	url = "https://blog.varigergo.hu"

[[start]]
	identifier = "social media"
	weight = 10
[[start]]
	name = "twitter"
	url = "https://twitter.com/powerwritergreg"
	weight = 18
	parent = "social media"
[[start]]
	name = "instagram"
	url = "https://instagram.com/gergo_vari"
	weight = 19
	parent = "social media"

[[start]]
	identifier = "portfolio"
	weight = 20
[[start]]
	name = "github"
	url = "https://www.github.com/gergovari"
	weight = 24
	parent = "portfolio"
[[start]]
	name = "linkedin"
	url = "https://www.linkedin.com/in/varigergo"
	weight = 26
	parent = "portfolio"


[[end]]
	identifier = "book a call"
	url = "https://calendly.com/gergovari/growth-consultation"
	weight = 1
